In [1]:
import numpy as np

In [3]:
#1
x = np.arange(9)
x

array([0, 1, 2, 3, 4])

In [12]:
£
x = np.zeros(12).reshape(3,4).astype(int)
print(x)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [15]:
#3
x = np.ones(6).reshape(2,3)
print(x)

[[1. 1. 1.]
 [1. 1. 1.]]


In [18]:
#4
x = np.arange(12).reshape(3, 4)
print(x.shape)
print(x.size)
print(x.ndim)

(3, 4)
12
2


In [4]:
#5
a = [10,20,30,40]
array = np.array(a,dtype=np.int64)
print(type(array))
print(array.dtype)

<class 'numpy.ndarray'>
int64


In [25]:
#6
x = np.arange(20)
yeni_dizi = x[(5<x) & (x<15)]
print(yeni_dizi)

[ 6  7  8  9 10 11 12 13 14]


In [30]:
#7,8
a = np.array([1,2,3])
b = np.array([4,5,6])
c = a+b
c

array([5, 7, 9])

In [31]:
#9
m = np.arange(1,26).reshape(5,5)
print(m)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [40]:
#10
print(m[1,:])
print(m[:, 2])

[ 6  7  8  9 10]
[ 3  8 13 18 23]


In [44]:
#11,12
x = np.random.randint(0,100,6).reshape(2,3)
print(x)
x_t = np.transpose(x)
print(x_t)

[[47 14 23]
 [32 24 46]]
[[47 32]
 [14 24]
 [23 46]]


In [48]:
#13,14 
x = np.array([1,2,np.nan,4,5,np.nan,7])
toplam = np.sum(np.isnan(x))
print(toplam)

2


In [52]:
#15,16
x = np.random.randint(0,1000,25).reshape(5,5)
print(x)
print(x.mean())
print(x.max())
print(np.std(x,axis=0))

[[664   8 890 862 207]
 [802 411 372 918 824]
 [736 377 643 355 464]
 [597 951 417 312 424]
 [687 339 529 704 579]]
562.88
951
[ 68.89818575 303.36670879 185.48466244 252.58376828 202.05801147]


In [3]:
#17
a = np.array([1,2]) 
b = np.array([3,4])
h_stack = np.hstack((a,b))
v_stack = np.vstack((a,b))
print(h_stack)
print(v_stack)

[1 2 3 4]
[[1 2]
 [3 4]]


In [5]:
#18,19
a = np.array([[1,2],[3,4]])
b= np.array([[5,6],[7,8]])
carpim = np.dot(a,b)
print(carpim)

[[19 22]
 [43 50]]


In [11]:
#20,21
a = np.random.uniform(0,100,25).reshape(5,5)
print(a)
ort = np.mean(a , axis=0)
yeni_matris = a - ort
print(yeni_matris)

[[96.13577235  4.39698175  4.92366467 26.82893625  3.31942319]
 [21.36912834 92.52803948 51.18637789 79.55203293 32.82429127]
 [27.62648149 99.05357655 56.83073595 11.19139279 16.84068935]
 [66.05805059 83.63123768 42.71171916 17.778949   18.3283163 ]
 [10.40141002 99.70468061 61.3184096  93.13157335 45.11902018]]
[[ 51.81760379 -71.46592146 -38.47051678 -18.86764061 -19.96692487]
 [-22.94904022  16.66513627   7.79219643  33.85545607   9.53794321]
 [-16.69168707  23.19067334  13.4365545  -34.50518407  -6.44565871]
 [ 21.73988203   7.76833447  -0.6824623  -27.91762787  -4.95803176]
 [-33.91675854  23.84177739  17.92422815  47.43499648  21.83267212]]


In [30]:
#22,23,24
c = np.array([[4,7],[2,6]])
det = np.linalg.det(c)
print(det)
inv = np.linalg.inv(c)
print(inv)
check = np.dot(c,inv)
birim = np.eye(2).astype(int)
if np.allclose(birim,check):
    print(check)
    print("Birim matris geldi işleminiz doğru")
else:
    print(check)
    print("Birim matris gelmedi işleminiz yanlış")

10.000000000000002
[[ 0.6 -0.7]
 [-0.2  0.4]]
[[1. 0.]
 [0. 1.]]
Birim matris geldi işleminiz doğru


In [39]:
#25
check = {}
veri = np.array([1, 2, 1, 4, 5, 2, 7, 1])
for i in veri:
    if i in check:
        check[i] = check[i]+1
    else: 
        check[i]=1
print(check)    

{np.int64(1): 3, np.int64(2): 2, np.int64(4): 1, np.int64(5): 1, np.int64(7): 1}


In [41]:
#26,27
dizi = np.random.randn(100)
print(dizi)
yeni_dizi = np.clip(dizi,-2,2)
print(yeni_dizi)


[-0.90933989  0.99045953  1.56098067 -1.96226542 -0.50367282 -0.34968591
 -0.93373669 -0.09491178  0.42596753 -0.13173169  0.40949991  0.26269864
  0.4681835   0.69992076 -0.46029874 -0.35145853 -1.16707877  2.00568396
 -0.65167513  0.44865074 -0.30924799  1.38830676 -1.5121614  -0.28858798
 -0.58087008  1.20955868  1.46107061  1.26178637  0.65558935  0.44865396
 -0.78814731  0.64211037 -0.44727325 -0.01073186  1.60739623 -0.27348485
  1.33952313 -0.01152683 -0.96566952 -1.70362463 -0.62151949 -0.73902821
 -1.39782772  0.37110911  1.03397183  1.0510643  -0.18218677  0.16939689
 -1.15558579  0.60681431 -0.46479318  0.1529672  -1.30816861  1.94075356
 -1.05961506 -0.19746759 -0.69425703 -0.58160901 -1.08305303  0.43106009
 -1.11103464  0.80793288 -0.28524439  1.92374437  0.98813716 -1.76908183
  0.12913574 -0.4940884  -0.70506722  0.41004969 -0.51757721 -1.33594586
 -0.50884691 -0.02650453 -1.21780508 -1.34457281 -1.22764613 -1.46690574
  0.47805863 -0.76332343  1.47929919 -0.5728669   0

In [44]:
#28,29
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])
inner = np.inner(v1,v2)
print(inner)
outer = np.outer(v1,v2)
print(outer)

32
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


In [49]:
#30
py_list = list(range(1000000))
np_array = np.array(py_list)

In [30]:
#Karar Tensöründe Eksen Tabanlı Filtreleme 
tensor = np.random.randint(0,1000, size=(5,20,8))
ort = np.mean(tensor, axis=(0,2))
print(f"Her bir zaman adımının ortalaması {ort}")
genel_ort = np.mean(ort)
yeni_tensor = tensor - genel_ort
print("Yeni tensörünüz")
print(yeni_tensor)
print(np.mean(yeni_tensor))


Her bir zaman adımının ortalaması [551.3   483.65  516.575 526.    499.475 479.325 487.225 492.15  490.575
 547.125 465.45  481.325 494.275 488.95  424.3   404.675 539.45  581.8
 574.625 505.75 ]
Yeni tensörünüz
[[[ 1.603e+02  2.963e+02  1.563e+02 -1.197e+02 -2.977e+02  7.330e+01
    3.183e+02  9.430e+01]
  [ 2.373e+02  6.930e+01 -2.737e+02 -2.970e+01  4.443e+02  4.293e+02
   -2.807e+02 -8.270e+01]
  [-4.097e+02  3.723e+02  7.530e+01 -4.127e+02  1.133e+02 -3.267e+02
   -2.077e+02 -1.407e+02]
  [ 2.363e+02  4.343e+02  1.943e+02 -4.597e+02 -7.570e+01  3.573e+02
   -3.667e+02  2.533e+02]
  [ 1.583e+02 -2.627e+02  2.903e+02 -3.737e+02 -1.837e+02 -1.067e+02
    4.213e+02  2.973e+02]
  [-3.017e+02 -1.747e+02 -1.787e+02 -4.197e+02 -6.670e+01 -4.657e+02
    6.330e+01  4.003e+02]
  [-3.917e+02  1.863e+02 -2.717e+02 -5.670e+01 -3.327e+02  4.153e+02
    3.863e+02  3.833e+02]
  [-8.170e+01  3.093e+02 -9.370e+01  4.753e+02  1.643e+02  1.593e+02
   -2.270e+01  5.230e+01]
  [ 4.833e+02  4.933e+02  2.

In [46]:
#50 adet noktanın 4 boyutlu uzaydaki koordinatlarını içeren (50, 4) boyutunda bir matris (A) ve 1 adet referans noktasını içeren (1, 4) boyutunda bir matris (B) oluşturun.
a = np.random.randn(50,4)
b = np.random.randn(1,4)
cikart = a - b 
kare_al = cikart ** 2
topla = np.sum(kare_al, axis = 1)
kokten_cikar = np.sqrt(topla)
print(kokten_cikar)
yakin = np.min(kokten_cikar)
print(f"En yakın noktanın mesafesi: {yakin}")
indeks = np.argmin(kokten_cikar)
print(f"A makrisindeki indeksi {indeks}")

[2.69520021 2.94814993 2.9257376  2.80493083 2.04988012 3.03310162
 3.20954187 3.77864729 4.66905481 5.08510987 3.22012425 2.31993424
 3.24382491 3.22486537 2.90900758 3.24664627 3.63714402 3.98727124
 3.25539972 2.71794731 4.88064316 3.46207002 3.19267716 3.40994317
 1.52105091 3.46253058 2.59753614 3.07109627 3.38124473 3.39366076
 4.11234694 5.17775888 2.80526798 2.84780438 3.14302222 3.97121326
 3.65436483 3.88012032 3.34809904 3.48582537 3.87010863 1.93773553
 3.70319917 2.4687595  2.85814517 4.11232646 2.55663455 3.84527494
 4.81355351 5.40382103]
En yakın noktanın mesafesi: 1.5210509098833087
A makrisindeki indeksi 24


In [39]:
#Finansal Volatilite Matrisi (Lineer Cebir & Dif)
matris = np.random.uniform(80,200,720).reshape(120,6)
fark = np.diff(matris,axis = 0)
degisim = fark / matris[:-1]
print(f"Yüzde değişim {degisim[:3]}")
cov = np.cov(degisim,rowvar = False)
print(f"Koveryans matrisi:\n {cov}") 
value,vector = np.linalg.eig(cov)
indeks = np.argmin(value)
en_kucuk_val = value[indeks]
en_kucuk_vek = vector[:,indeks]
print(en_kucuk_val)
print(en_kucuk_vek)


Yüzde değişim [[-0.42904316  0.77268247 -0.3148283   0.06737373  0.01101937  0.51559711]
 [ 0.45072891 -0.42461809  0.58918538  0.55243943 -0.58003686 -0.32890215]
 [ 0.43445965  0.82239676 -0.47579974 -0.26223839  0.14148756  0.90704191]]
Koveryans matrisi:
 [[ 0.17375149  0.01423054 -0.02479481 -0.01287477 -0.016056    0.00157182]
 [ 0.01423054  0.15983968 -0.01876528 -0.0182114   0.01405228  0.00767787]
 [-0.02479481 -0.01876528  0.1826218   0.00145836 -0.04483096 -0.02783322]
 [-0.01287477 -0.0182114   0.00145836  0.17073046 -0.0044854  -0.00051951]
 [-0.016056    0.01405228 -0.04483096 -0.0044854   0.19392168  0.04160674]
 [ 0.00157182  0.00767787 -0.02783322 -0.00051951  0.04160674  0.15923419]]
0.12183520543689426
[ 0.48141508 -0.02612299  0.48674135  0.15602185  0.62306971 -0.34362957]


In [60]:
#İklim Anomali Tespiti (3D Eksen Yönetimi)
matris = np.random.randint(15,35,size=(10,30,2))
matris[:,:,1] = np.random.randint(50,80,size=(10,30))
ort = np.mean(matris,axis=(0,1))
print("Ortalama sıcaklık", ort[0])
print("Ortalama nem", ort[1])
vector = ort.reshape(1,1,2)
print("Ortalama vektörü",vector)
yeni_matris = matris - vector
print(yeni_matris)

Ortalama sıcaklık 24.723333333333333
Ortalama nem 63.25666666666667
Ortalama vektörü [[[24.72333333 63.25666667]]]
[[[  6.27666667  -5.25666667]
  [  5.27666667   6.74333333]
  [ -0.72333333  11.74333333]
  [  1.27666667   2.74333333]
  [ -7.72333333  13.74333333]
  [  6.27666667 -11.25666667]
  [ -5.72333333  11.74333333]
  [  4.27666667  10.74333333]
  [ -6.72333333   2.74333333]
  [  6.27666667  -2.25666667]
  [ -8.72333333  -4.25666667]
  [  6.27666667  -3.25666667]
  [  8.27666667  -6.25666667]
  [  9.27666667   7.74333333]
  [ -8.72333333   2.74333333]
  [ -7.72333333  -6.25666667]
  [ -6.72333333  -7.25666667]
  [  2.27666667  15.74333333]
  [ -0.72333333  -7.25666667]
  [ -3.72333333  -3.25666667]
  [  3.27666667  -1.25666667]
  [ -2.72333333   4.74333333]
  [ -6.72333333   3.74333333]
  [ -4.72333333  15.74333333]
  [ -1.72333333 -10.25666667]
  [ -2.72333333 -12.25666667]
  [  5.27666667   3.74333333]
  [  3.27666667  -3.25666667]
  [  8.27666667  -6.25666667]
  [ -9.72333333

In [80]:
#Çoklu Eksen Sıralaması ve İndeksleme
matris = np.random.randint(0,100,size=(100,3))
sira_indeks = np.lexsort((matris[:,0],-matris[:,2]))
sira_puan = matris[sira_indeks]
print(sira_puan[:10])
print(f"En iyi 10 öğrencinin ortalaması {np.mean(sira_puan[:10])}")

[[20  1 99]
 [38 18 99]
 [ 0 42 97]
 [38 62 97]
 [66 94 97]
 [69 21 96]
 [93 85 94]
 [64 19 93]
 [66 25 93]
 [73 44 90]]
En iyi 10 öğrencinin ortalaması 63.1


In [ ]:
#Eşitsiz Gruplama ve İstatistik (Split & Aggregate)
veri = np.random.randn(1000)
indek

In [91]:
#NaN Değerlerini Koşullu Doldurma (Missing Data Imputation)
matris = np.random.randn(20, 5)
rastgele_satirlar = np.random.choice(20, size=10, replace=True)
rastgele_sutunlar = np.random.choice(5, size=10, replace=True)

for i in range(10):
    matris[rastgele_satirlar[i], rastgele_sutunlar[i]] = np.nan
medyan = np.nanmedian(matris, axis=0)
print("Sütunların medyanları\n",medyan)
yeni = np.where(np.isnan(matris),medyan,matris)
print(yeni)
print(f"\nDoldurulmuş matristeki NaN sayısı: {np.sum(np.isnan(yeni))}")



Sütunların medyanları
 [-0.50546514  0.15934419 -0.28790558  0.35967522  0.12835279]
[[ 1.70858985 -0.67923479 -0.20993374  0.48587677 -1.45361584]
 [-0.50546514 -0.23642438  0.02783974  0.59370499 -0.0549614 ]
 [ 0.94561209  0.15934419 -0.73861815 -0.37089544 -1.33484437]
 [ 0.36823911 -1.15536559 -2.84559927  1.17851214 -0.18880241]
 [-0.06711407 -1.02724914 -0.36587743 -1.14269047  0.78890321]
 [ 0.08332296  0.77523476  0.16634607  0.3485396  -0.43122015]
 [ 0.74216382 -1.74386752 -1.78205769 -3.10503197  0.09141315]
 [-1.29997493  1.17995943 -0.72475699  0.35967522 -0.47963376]
 [-1.89029648  0.28884473 -0.28790558  0.37081083 -1.44561058]
 [-0.67391327  0.15934419 -0.94838555 -1.54188753 -0.37471068]
 [ 0.67643689  0.97117964 -0.7235066   1.96906875  1.91104569]
 [-1.60555458  1.28672289  0.88905582 -0.25819889  0.77361703]
 [-0.5995245   0.15934419  0.21775277  0.35967522  0.16529243]
 [-0.50546514  0.74681146 -0.68739296  0.38145557  0.12835279]
 [ 1.64218131  0.75561782  2.2936

In [100]:
#Özel Birleştirme ve İndeksleme
a = np.random.randint(0,100,size=(10,3))
b = np.random.randint(0,100,size=(10,3))
yeni = np.c_[a[:,0],b[:,1],a[:,2]]
print(yeni)
medyan = np.median(yeni[:,0])
print("Medyan:",medyan)
sapma = np.std(yeni[:,1])
print("Standard sapma: ",sapma)
toplam =np.sum(yeni[:,2])
print("Toplam:",toplam)
vektör = np.array([medyan,sapma,toplam])
print(vektör)

[[ 4 69 67]
 [28 56 71]
 [34 20 46]
 [44 39 29]
 [30 76 93]
 [71 14 71]
 [87 97 29]
 [68 61 31]
 [62 66 96]
 [29 42 15]]
Medyan: 39.0
Standard sapma:  24.24871130596428
Toplam: 548
[ 39.          24.24871131 548.        ]
